apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-deployment
  template:
    metadata:
      labels:
        app: front-deployment
    spec:
      containers:
        - name: front
          image: ghcr.io/goodfood-cesi/front:latest
      imagePullSecrets:
        - name: ghcr-secret
