apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: front-cert
  namespace: default
spec:
  commonName: ksu.li
  secretName: front-cert
  dnsNames:
    - ksu.li
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer